// packages/generator-npm-portlet-extender/src/target-react-portlet/templates/src/AppComponent.js
import React from 'react';
import ReactDOM from 'react-dom';

export default class extends React.Component {
	render() {
		return (
            <div>
				<div>
					<span class="tag">Portlet Namespace:</span> 
					<span class="value">{this.props.portletNamespace}</span>
				</div>
				<div>
					<span class="tag">Context Path:</span> 
					<span class="value">{this.props.contextPath}</span>
				</div>
				<div>
					<span class="tag">Portlet Element Id:</span>
					<span class="value">{this.props.portletElementId}</span>
				</div>
			</div>
		);
	}	
}

// packages/generator-npm-portlet-extender/src/app/templates/angular/src/app/app.component.ts
import { Component } from '@angular/core';

import LiferayParams from '../types/LiferayParams'

// TODO: extract markup to an HTML file
@Component({
	template: `
		<div class="AppComponent">
		  <div class="portletNamespace">
			  Portlet Namespace: 
			  <span class="value">{{params.portletNamespace}}</span>
		  </div>

		  <div class="contextPath">
			  Context Path: 
			  <span class="value">{{params.contextPath}}</span>
		  </div>

		  <div class="portletElementId">
			  Portlet Element Id: 
			  <span class="value">{{params.portletElementId}}</span>
		  </div>
		</div>
	`,
})
export class AppComponent {
	params: LiferayParams;
}

<div class="AppComponent">
	<div class="portletNamespace">
		Portlet Namespace: 
		<span class="value">{{params.portletNamespace}}</span>
	</div>

	<div class="contextPath">
		Context Path: 
		<span class="value">{{params.contextPath}}</span>
	</div>

	<div class="portletElementId">
		Portlet Element Id: 
		<span class="value">{{params.portletElementId}}</span>
	</div>
</div>
